### PR TITLE
[14.0][ADD] partner_ship

### PR DESCRIPTION
**Pull request by ChristianSantamaria**
Adds new ship fields to contacts

### CODE REVIEW

**Comment by ChristianSantamaria** [comment]
Kanban Update
imagen

**Comment by dalonsod** [comment]
@ChristianSantamaria move `onchange` to computed writable fields and minor changes.

Pending:
- Add `ship` and `ship_name` to tree view, as `optional="show"` fields.
- When `ship` is selected, make required `ship_name`.
- `ship_name` field bigger in `form` view, if possible.
- Make _Ship features_ tab the first one, when visible.
- Create a `ROADMAP` with a future improvement: adding search by `ship_name` in Many2one `res.partner` fields.

**Review by dalonsod — APPROVED** [review]
LGTM for a first version. Please generate `i18n` files and squash commits

**Comment by dalonsod** [comment]
Ready to merge!

**Pull request merged**
